### ISSUE TITLE
Partial bounding boxes

### ISSUE THREAD

**Issue by alex5806** [hukkelas/DeepPrivacy#51]
Is it possible to anonymize only a part of a face using bounding boxes? Using a custom im_bboxes with a high truncation level gives this traceback because z_shape is 0 in the first dimension
```
Traceback (most recent call last):
  File "DeepPrivacy/anonymize.py", line 5, in <module>
    cli.main()
  File "DeepPrivacy/deep_privacy/cli.py", line 142, in main
    anonymizer.anonymize_image_paths(image_paths, image_target_paths, [np.array([[250,400,500,550]])])
  File "DeepPrivacy/deep_privacy/inference/anonymizer.py", line 61, in anonymize_image_paths
    anonymized_images, image_annotations = self.detect_and_anonymize_images(
  File "DeepPrivacy/deep_privacy/inference/anonymizer.py", line 43, in detect_and_anonymize_images
    anonymized_images = self.anonymize_images(
  File "/usr/lib/python3/dist-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "DeepPrivacy/deep_privacy/inference/deep_privacy_anonymizer.py", line 74, in anonymize_images
    z = infer.truncated_z(
  File "DeepPrivacy/deep_privacy/inference/infer.py", line 96, in truncated_z
    while z.abs().max() >= truncation_level:
RuntimeError: operation does not have an identity.
```

Without a truncation level the model outputs an identical image without changes

**Comment by hukkelas** [comment]
> Is it possible to anonymize only a part of a face using bounding boxes?

It should be possible by editing the code, however, I would expect the results to be severly worse as the model is trained for full faces only. 
I believe your error originates from an error in the inputted im_bboxes. The input should be a list of [im_bboxes](https://github.com/hukkelas/DeepPrivacy/blob/d6903f77e7bf37073a0d0692108cb3dd42ec1eb8/deep_privacy/detection/detection_api.py#L59). 
If Z shape is 0 in the first dimension is caused by mask or image being 0 in the first dimension.
This might be caused by a implementation bug in the code when there is no faces detected, but this could be skipped by checking if no faces are present before anonymizing each face. I don't have time to look into this, but could look at it later if you can give code to reproduce the error.

> Without a truncation level the model outputs an identical image without changes
This is expected.

**Comment by alex5806** [comment]
Thank you for the response. If the results will be severely worse then it is probably not worth it.

I gave a list of im_bboxes by using the code
`anonymizer.anonymize_image_paths(image_paths, image_target_paths, [np.array([[250,400,500,550]])])` (a bounding box around part of a face) and patched `RCNNDetector.get_detections` so it will not overwite im_bboxes when `not None`.
